### ISSUE TITLE
Persona 4: Dancing All Night [PCSE00764]

### ISSUE THREAD

**Issue by N30117** [Vita3K/compatibility#2651] opened 2024-09-20 18:04 UTC
# App summary
- App name: Persona 4 - Dancing All Night
- App serial: PCSE00764
- App version: 1.00

# Vita3K summary
- Version: v0.2.0
- Build number: 3647
- Commit hash: https://github.com/vita3k/vita3k/commit/77abeaa
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: N30117
- OS: Windows 11
- CPU: AMD Ryzen 5 5600
- GPU: NVIDIA GeForce RTX 3060 TI
- RAM: 16 GB

# Issues
Whenever attempting to play the game cross (X) is confused for the start button, even when unbinded cross is still recognized as the start button. I am using a Dualsense Wireless Controller via USB-C

# Screenshots
![keybindings](https://github.com/user-attachments/assets/91800be3-cd30-4f44-9a39-051bf85c51d8)
![when crossed is press](https://github.com/user-attachments/assets/1a5de972-1c14-41f0-840c-534e65b9f4c8)

# Log
[vita3k.log](https://github.com/user-attachments/files/17078979/vita3k.log)

# Recommended labels
- Ingame +
- Controller Issue
- Input Bug

**Comment by Panderner** [comment] 2024-09-21 03:17
Duplicate of #175

**Comment by nishinji** [comment] 2024-09-21 03:51
> Duplicate of #175

thank you!

**Closed by nishinji** 2024-09-21 03:51 UTC
Labels: input bug, Ingame +, controller issue
