### ISSUE TITLE
The Legend of Heroes: Trails in the Sky SC Evolution [PCSG00489]

### ISSUE THREAD

**Issue by nishinji** [Vita3K/compatibility#1049] opened 2022-11-03 05:05 UTC
# App summary
- App name: 英雄伝説 空の軌跡 SC Evolution
- App serial: PCSG00489
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 2897
- Commit hash: https://github.com/vita3k/vita3k/commit/711e8295
- CPU backend: Dynarmic
- GPU backend: Vulkan

# Test environment summary
- Tested by: nishinji
- OS: Windows 10
- CPU: Ryzen 9 3950x
- GPU: RTX 3060ti
- RAM: 32 GB

# Issues
only playable with vulkan
# Screenshots
locked here
![スクリーンショット (464)](https://user-images.githubusercontent.com/107111782/199650879-e5ddab7c-5769-4838-9e03-20b18b40cbd1.png)
![スクリーンショット (461)](https://user-images.githubusercontent.com/107111782/199650891-91eee434-f062-4459-9166-f987020ab99c.png)
![スクリーンショット (462)](https://user-images.githubusercontent.com/107111782/199650919-4f2cee05-80f0-43d6-a8ae-7ecb4d716f61.png)
# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/9925721/vita3k.log)
# Recommended labels
ingame -
audio missing

**Comment by othmanead** [comment] 2022-11-04 18:24
duplicate of https://github.com/Vita3K/compatibility/issues/608

**Closed** 2022-11-04 18:25 UTC
Labels: duplicate issue
