### ISSUE TITLE
The Legend of Heroes: Trails in the Sky FC Evolution [PCSG00488]

### ISSUE THREAD

**Issue by nishinji** [Vita3K/compatibility#1050] opened 2022-11-03 05:23 UTC
# App summary
- App name: 英雄伝説 空の軌跡 FC Evolution
- App serial: PCSG00488
- App version: 1.00

# Vita3K summary
- Version: v0.1.6
- Build number: 2897
- Commit hash: https://github.com/vita3k/vita3k/commit/711e8295
- CPU backend: Dynarmic
- GPU backend: OpenGL

# Test environment summary
- Tested by: nishinji
- OS: Windows 10
- CPU: Ryzen 9 3950x
- GPU: RTX 3060ti
- RAM: 32 GB

# Issues
only playable with opengl
# Screenshots
![スクリーンショット (466)](https://user-images.githubusercontent.com/107111782/199652619-30185348-68bf-45c0-abec-9eacbf339e54.png)
![スクリーンショット (465)](https://user-images.githubusercontent.com/107111782/199652646-b03d35bd-5e75-401c-82a1-2e68bbf72af3.png)
locked here
![スクリーンショット (467)](https://user-images.githubusercontent.com/107111782/199652658-04b68d6d-1567-4148-ac1d-dace15c6835c.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/9925794/vita3k.log)
# Recommended labels
ingame -
audio missing

**Comment by othmanead** [comment] 2022-11-04 18:24
duplicate of https://github.com/Vita3K/compatibility/issues/514

**Closed** 2022-11-04 18:24 UTC
Labels: duplicate issue
