### ISSUE TITLE
Pinball Arcade [PCSE00065]

### ISSUE THREAD

**Issue by Zach-star1** [Vita3K/compatibility#2281] opened 2023-08-03 11:09 UTC
# App summary
- App name: Pinball Arcade
- App serial: [PCSE00065]
- App version: 1.34

# Vita3K summary
- Version: v0.1.8
- Build number: 3311
- Commit hash: https://github.com/vita3k/vita3k/commit/5bd8b3b 
- CPU backend: Dynarmic.
- GPU backend: OpenGL

# Test environment summary
- Tested by: Zach-star1
- OS: Windows 11
- CPU: Intel i7-8565u
- GPU: NVIDIA mx130
- RAM: 16 GB

# Issues
Very weird lighting/reflection bug on the ball (it could possibly affect other minor lighting effects). When ingame the first time you play a table the lighting effects on the ball are messed up; then, if you exit the table and try again the lighting effects on the ball are completely fixed (and are also fixed for any other table you try within the same session). When you close the emulator and reopen the app the bug represents in the exact same way: it only affects the first game when you open the emulator.

# Screenshots
<img width="960" alt="screen 1" src="https://github.com/Vita3K/compatibility/assets/139509866/46c8753f-268a-4f9c-a850-1b9aa289df4c">
First game on the tales of the Arabian night, where the lighting on the ball is messed up

<img width="960" alt="screen 2" src="https://github.com/Vita3K/compatibility/assets/139509866/5607ebcb-763c-429a-9e41-db5a3d649a3f">
Second game on tales of the Arabian night (within the same session), where the lighting on the ball is fixed

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/12250067/vita3k.log)

# Recommended labels
- Playable
- Graphic bug

**Comment by Zach-star1** [comment] 2023-08-03 14:29
Sorry, but I didn't know where to post the issue and by accident I opened a new Arcade Pinball page (and now I don't know how to delete it).
Now I posted this bug as a comment under the Pinball Arcade "official issue" that is the number 830 https://github.com/Vita3K/compatibility/issues/83 but I don't know if it is correct like this

**Comment by nishinji** [comment] 2023-08-03 21:08
duplicate of #830

**Closed by nishinji** 2023-08-03 21:08 UTC
