### ISSUE TITLE
Dragon's Crown [PCSE00019]

### ISSUE THREAD

**Issue by CoffeeBrewer64** [Vita3K/compatibility#1111] opened 2023-01-06 21:40 UTC
# App summary
- App name: Dragon's Crown
- App serial: PCSE-00019]
- App version: v1.00

# Vita3K summary
- Version: v0.1.6 
- Build number: 2968-0df79bb8
- Commit hash: https://github.com/Vita3K/Vita3K/commit/7c8db9eab686dbb34c3582266f102a6a660d5258
- CPU backend:  Dynamic
- GPU backend: OpenGL

# Test environment summary
- Tested by: CoffeeBrewer64
- OS: Kali Linux 2022.4 Debian 11 Bullseye-based. Kernel version 7.1 (I think)
- CPU: Intel
- GPU: Intel Mesa iGPU
- RAM: 8gb
- Device: Lenovo Thinkpad T450, with some changes

# Issues
The audio is often slow or choppy.

# Screenshots
![image](https://user-images.githubusercontent.com/69767396/211102486-0be3b1de-f194-4172-9277-a9d5008882fb.png)

# Log

[vita3k.log](https://github.com/Vita3K/compatibility/files/10363275/vita3k.log)

# Recommended labels

- Playable
- Audio bug

**Comment by Macdu** [comment] 2023-01-07 12:02
Duplicate of #401

**Closed by Macdu** 2023-01-07 12:02 UTC
Labels: audio bug, Playable
