### ISSUE TITLE
この素晴らしい世界に祝福を！ATTACK OF THE DESTROYER [PCSG01093]

### ISSUE THREAD

**Issue by meowthed** [Vita3K/compatibility#458] opened 2021-01-16 06:08 UTC
# App summary
- App name: この素晴らしい世界に祝福を！ATTACK OF THE DESTROYER
- App serial: PCSG01093
- App version: 1.00

# Vita3K summary
- Version: v0.1
- Build number: 1827
- Commit hash: https://github.com/Vita3K/Vita3K/commit/0f2aabb900ddd27078df540bfe8f1d177ff0445d 

# Test environment summary
- Tested by: Arnold Secret
- OS: Windows 10
- CPU: Intel Core i7-4500U
- GPU: NVIDIA Geforce GT 740M
- RAM: 8 GB

# Issues
Reaches to MAGES logo, then crashes.

# Screenshots
![Untitled](https://user-images.githubusercontent.com/41223243/104798751-31969e00-5804-11eb-9327-35f974195b44.png)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/5823941/vita3k.log)

**Comment by arnoldsecret** [comment] 2021-01-16 07:06
Closed, dupe of https://github.com/Vita3K/compatibility/issues/109

**Closed by arnoldsecret** 2021-01-16 07:06 UTC
