### ISSUE TITLE
Ben 10™ Galactic Racing [PCSE00024]

### ISSUE THREAD

**Issue by AlphaN00b** [Vita3K/compatibility#587] opened 2022-02-27 18:28 UTC
# App summary
- App name: Ben 10™ Galactic Racing
- App serial: PCSE00024
- App version: 1.00

# Vita3K summary
- Version: v0.1.4
- Build number: 2433
- Commit hash: https://github.com/Vita3K/Vita3K/commit/b8f0accb770bae2b756241da99d01c6f7c660270 
- CPU backend: Dynarmic         

                          

# Test environment summary
- Tested by: AlphaN00b
- OS: Windows 10
- CPU: AMD ryzen 3400g
- GPU: AMD vega 11
- RAM: 16 GB

# Issues
the game has some stutter issues but is defenitelly playable, most of the audio missing + some audio glitches 

# Screenshots
![](https://i.imgur.com/TVv49UQ.png)
![](https://i.imgur.com/gxK7JzV.png)
# Log

[PCSE00024 - [Ben 10™ Galactic Racing].log](https://github.com/Vita3K/compatibility/files/8153668/PCSE00024.-.Ben.10.Galactic.Racing.log)

# Recommended labels

- Playable
- audio missing
- audio bug

**Comment by benderscruffy** [comment] 2022-06-02 04:05
duplicate of #202

**Closed** 2022-06-02 07:18 UTC
