### ISSUE TITLE
Trails in the Sky FC Evolution [PCSG00488]

### ISSUE THREAD

**Issue by Zarukyun** [Vita3K/compatibility#1737] opened 2023-06-26 20:34 UTC
# App summary
- App name: 英雄伝説 空の軌跡 FC Evolution English Patched 
- App serial: PCSG00488
- App version: 1.02

# Vita3K summary
- Version: v0.1.8
- Build number: 3233-a6f64367
- Commit hash: https://github.com/vita3k/vita3k/commit/[commit] 
- CPU backend: Dynamic
- GPU backend: Vulcan + OpenGL (Vulcan has better performance)

# Test environment summary
- Tested by: Zarukyun
- OS: Windows 11
- CPU: Intel i7 13700K 3.40 GHz 
- GPU: NVIDIA RTX 4090 
- RAM: 32GB

# Issues
- Black hole during battles, during animations it can disappear. Otherwise perfect.
- Visible rectangle around the animated eyes of the portraits
- Flashing red image during transitions
# Screenshots

![image_2023-06-26_212744533](https://github.com/Vita3K/compatibility/assets/137831750/1bb6edfb-2062-4bfa-af65-dc10bbd7f793)

![image_2023-06-26_211824380](https://github.com/Vita3K/compatibility/assets/137831750/840ae200-333a-4c5e-880a-211ba4257ba6)
![image_2023-06-26_212628348](https://github.com/Vita3K/compatibility/assets/137831750/ffa3707e-98a7-42d2-8d0c-ac7e56316ee1)
![image_2023-06-26_213020820](https://github.com/Vita3K/compatibility/assets/137831750/0622b87e-2a4a-4699-91e4-84fb32c4833f)
![image_2023-06-26_211844127](https://github.com/Vita3K/compatibility/assets/137831750/a920c82a-e87c-4512-80a8-784024b13866)
![image_2023-06-26_211916150](https://github.com/Vita3K/compatibility/assets/137831750/3a6427cb-f409-49fa-a385-ab2804a50175)

# Log
[vita3k.log](https://github.com/Vita3K/compatibility/files/11873894/vita3k.log)

# Recommended labels

- Graphics Bug
- Ingame+

**Comment by othmanead** [comment] 2023-06-26 21:47
this is duplicate of https://github.com/Vita3K/compatibility/issues/514, write this report as a comment there

**Closed by othmanead** 2023-06-26 21:47 UTC
